spring.application.name=backend

# Active Profile (로컬 개발 시 dev, 배포 시 prod)
spring.profiles.active=dev

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.connection.charSet=UTF-8
spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8

# SQL 바인딩 파라미터 로깅
logging.level.org.hibernate.orm.jdbc.bind=trace

# 파일 업로드 용량 제한
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
